spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websocket_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
    mode: HTML

  security:
    user:
      name: admin
      password: admin123

server:
  error:
    whitelabel:
      enabled: false


